### ISSUE TITLE
Can GoogleAnalyticsTracker support .NET3.5 targeted WinForm project?

### ISSUE THREAD

**Issue by gennadiycivil** [maartenba/GoogleAnalyticsTracker#100]
Trying to get NuGet package for project that is targeted to .NET3.5, getting this.

What in GoogleAnalyticsTracker is requiring .NET 4.x? Can it support 3.5?
Thanks
 

Install-Package : Could not install package 'GoogleAnalyticsTracker.Core 4.1.12'. You are trying to install this package into a project that 
targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that 
framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package GoogleAnalyticsTracker.Simple
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM>

**Comment by gandarez** [comment]
We could think different. Is it possible to migrate your project to .Net 4?

**Comment by gennadiycivil** [comment]
Unfortunately we can't move to .Net 4 due to  client limitations
What is it that the tracker needs in 4 that is not available in 3.5?
Thank you

Typos curtesy of iPhone

On Jan 20, 2016, at 18:26, Carlos Henrique Guard?o Gandarez <notifications@github.com<mailto:notifications@github.com>> wrote:


We could think different. Is it possible to migrate your project to .Net 4?

-

**Comment by maartenba** [comment]
All the async stuff. Feel free to clone a 1.8.x tag, this may compile to .net 3.5 if you change the target frameworks
