### ISSUE TITLE
Session id is written to ClientId? (all users count as new users?)

### ISSUE THREAD

**Issue by AnderssonPeter** [maartenba/GoogleAnalyticsTracker#107]
Im a bit confused i have a WPF application where i use `GoogleAnalyticsTracker.Core` and  `GoogleAnalyticsTracker.Simple`, version: 4.1.40.0.

But when i use `TrackAsync` it seems all users count as new users, so i looked at the source code and `TrackAsync` calls `this.SetRequired` which in turn calls `parameters.ClientId = this.AnalyticsSession.GenerateSessionId()` and `ClientId` equals to `cid` and the description for `cid` is: 

> Required for all hit types.
> 
> This anonymously identifies a particular user, device, or browser instance. For the web, this is generally stored as a first-party cookie with a two-year expiration. For mobile apps, this is randomly generated for each particular instance of an application install. The value of this field should be a random UUID (version 4) as described in http://www.ietf.org/rfc/rfc4122.txt
> 

Why on earth does it write a session id to cid, this way all users will count as new users?

**Comment by maartenba** [comment]
There's no way we can add a built-in session tracker (everyone may see a session as something different). You can create your own tracking logic and supply it into the library.

**Comment by AnderssonPeter** [comment]
That's not the point?
A session is in this case the same as a client? so no client can have 2 different sessions? isn't that fundamental flawed? (i guess `GenerateSessionId()` is a misleading name as its not the session id you are generating its the client id?)

But i get the point i have to override `GenerateSessionId()` to correct this issue.

**Comment by maartenba** [comment]
In your application, a session may be "one run of the app". In a web application, it may be coming from a cookie. Same with client. I understand that it's not the point, but every use case is different so providing client id and session id manually is the only way to properly distinguish :)

**Comment by AnderssonPeter** [comment]
My point was that its hard to know that you have to override `GenerateSessionId()` to identify a unique visitor when its named Session and not Client.
I mean i had to look at the source code to figure out that even if i set `ClientId` it overwritten by `GenerateSessionId()`.

Im my world a Client and a Session are two fundamentally different things no matter what type of application it is? (sure for the run only once per pc app this doesn't matter, but for the rest it does).

**Comment by maartenba** [comment]
Do feel free to propose a change, happy to accept it.

**Comment by AnderssonPeter** [comment]
To make it less confusing i would rename `GenerateSessionId` to `GenerateClientId` or `GetClientId` but that would break a lot of existing applications so i guess thats out of the question.

So why not just change
```
parameters.ClientId = this.AnalyticsSession.GenerateSessionId();
```
to
```
if (string.IsNullOrWhiteSpace(parameters.ClientId))
{
	parameters.ClientId = this.AnalyticsSession.GenerateSessionId();
}
```
That way the programmer can set `ClientId` on their own without the framework overwriting it?
Any thoughts?

**Comment by maartenba** [comment]
A fresh build is on its way to NuGet :-) (4.1.41 should be there in ~30 minutes)
