### ISSUE TITLE
The given filter instance must implement one or more of the following filter interfaces: IAuthorizationFilter, IActionFilter, IResultFilter, IExceptionFilter.

### ISSUE THREAD

**Issue by mikemike396** [maartenba/GoogleAnalyticsTracker#109]
I have the GoogleAnalyticsTracker.WebAPI installed. Getting this exception 'System.InvalidOperationException' Any help?

```
 public class FilterConfig
 {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
            filters.Add(new ActionTrackingAttribute(
               "xx-xxxxxxx-x", "url",
               action => action.ControllerContext.ControllerDescriptor.ControllerName == "Api")
            );
        }
 }
```

**Comment by maartenba** [comment]
Can you double check the package used? (there are two for web api depending on the version)

**Comment by mikemike396** [comment]
I am using Web API 2 dependency. 

If I do something like this it runs fine but does not log to Google Analytics (https://forums.asp.net/t/1835666.aspx)
FilterConfig.cs:

```
public static void RegisterHttpFilters(HttpFilterCollection filters)
{
    filters.Add(new ModelValidationFilterAttribute());
}
```
Global.ascx.cs:

`FilterConfig.RegisterHttpFilters(GlobalConfiguration.Configuration.Filters);`

![screen shot 2016-11-06 at 7 36 58 am](https://cloud.githubusercontent.com/assets/14999806/20037720/eef4d9ea-a3f3-11e6-804f-984554825a68.png)
![screen shot 2016-11-06 at 7 37 03 am](https://cloud.githubusercontent.com/assets/14999806/20037721/eefea63c-a3f3-11e6-8bff-d3419aeb54c9.png)

**Comment by maartenba** [comment]
Will see if I can find some time to debug

**Comment by gandarez** [comment]
@maartenba actually what's happening is that WebApi2 does not reference any Mvc library which in this case is needed when registering a global filter (like MVC does).

There're 2 ways to follow. The first one is to reference Mvc library and implement the interface System.Web.Mvc.IActionFilter and the other one is to guide the folks to use as an HTTP filter (Class attribute ) like so:
```C#
[GoogleAnalyticsTracking]
public class ApiBase : ApiController { }

```

**Comment by mikemike396** [comment]
This works great! Thank You
