### ISSUE TITLE
GoogleAnalyticsTracker.WebApi.AsyncActionFilterAttribute Exception

### ISSUE THREAD

**Issue by mikemike396** [maartenba/GoogleAnalyticsTracker#110]
Getting the current error only under certain calls. WebAPI 2.0. Any thoughts?

{"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at GoogleAnalyticsTracker.WebApi.AsyncActionFilterAttribute.<ExecuteActionFilterAsync>d__1.MoveNext()"}

```
using GoogleAnalyticsTracker.WebApi;
using System;

namespace API.Analytics
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, Inherited = true, AllowMultiple = true)]
    public class GoogleAnalytics : ActionTrackingAttribute
    {
        public GoogleAnalytics() : base("xx-xxxxxxx-x") { }
    }
}
```

**Comment by maartenba** [comment]
Try GoogleAnalyticsTracker.WebAPI2 package

**Comment by mikemike396** [comment]
I found out that this line is what is causing the crash. Any idea? If I remove this line it works fine, and if I comment the GoogleAnalytics decoration on this method it works fine.

`HttpContext.Current.Request.ServerVariables["REMOTE_HOST"].ToString()`

**Comment by maartenba** [comment]
This line is nowhere in the codebase? Are you using the WebAPI2 package? Which version?
