### ISSUE TITLE
Feature Request - Tracking Crashes

### ISSUE THREAD

**Issue by RayyanTahir** [maartenba/GoogleAnalyticsTracker#114]
Hi,

I've used GoogleAnalyticsTracker for some time to track changes in screen views in my desktop application. I wanted to request if you could please find some time to add a crash reporting feature, such that I could send my crash reports to Google Analytics as well.

Thanks,

**Comment by maartenba** [comment]
Should be possible using the `Tracker` class. Just wire it up to a global exception handler and you should be good (but something like HockeyApp or AppInsights may be a better choice for that type of reporting)

**Comment by RayyanTahir** [comment]
Thank you, I'm working on WPF for desktop application development for which i'm using GoogleAnalyticsTracker.Simple. Under that namespace I only have the ability to Track 'pageview' or 'screenview'. Please advise.

Thanks again.

**Comment by maartenba** [comment]
`TrackEventAsync` should be there too?
