### ISSUE TITLE
Hostname is not tracked in SimpleTracker

### ISSUE THREAD

**Issue by rolandh** [maartenba/GoogleAnalyticsTracker#115]
_If you do need to track actual user data, it can be set on the Tracker object using its properties like Hostname, Language, UserAgent and so on._

I had a look through the source code and if you are using SimpleTracker the Hostname field is never used anywhere in the source code. Google analytics reports Hostname is "not set" when I set it.

Should the function TrackPageViewAsync in PageViewTrackerExtensions not be using the hostname somewhere?

**Comment by maartenba** [comment]
It should. Are you up for a PR? :-)

**Comment by rolandh** [comment]
Ok great. I wanted to make sure I wasn't doing something wrong first.

I will let you know when it is complete.

**Comment by rolandh** [comment]
Am I looking in the right location?

            var pageViewParameters = new PageView
            {
                DocumentTitle = pageTitle,
                DocumentLocationUrl = pageUrl,
                CacheBuster = tracker.AnalyticsSession.GenerateCacheBuster(),
                DocumentHostName = "OptionalHostName.com",  <<< hostname goes here???
            };

**Comment by maartenba** [comment]
That should be the one indeed

**Comment by rolandh** [comment]
Ok PR submitted

**Comment by maartenba** [comment]
And accepted :-) Fresh version on nuget, too. Thanks, @rolandh !
