### ISSUE TITLE
Error installing on ASP.Net Core 1.1

### ISSUE THREAD

**Issue by DonnieRich** [maartenba/GoogleAnalyticsTracker#118]
Hi,
I'm trying to install your package on a test Web API I've created.
The project is based on .NET Framework 4.5.2 with EntityFrameworkCore.InMemory v 1.1.2

Is there something I can do to make it work, are you developing a new version compatible with ASP.Net Core or I just need to create a new test environment based on .NET Framework 4.5?

**Comment by maartenba** [comment]
4.5.2 should work. .net core currently not planned.

**Comment by nfarrell** [comment]
Hi @maartenba, is there a reason .Net Core isn't planned for this? If not, I can take a stab at it over the next few weeks?

**Comment by maartenba** [comment]
Time, mostly. Feel free to take a stable, would appreciate the effort very much!

**Comment by maartenba** [comment]
Closing issue for now. Feel free to re-open if still needed. (do check https://github.com/maartenba/GoogleAnalyticsTracker/pull/154 for newer MVC vrsions)
