### ISSUE TITLE
WebRequestExtensions not used

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#119]
I have searched the code and the `WebRequestExtensions` is not used, is it right? If so, then it should be removed. Otherwise I suggest to use the `ManualResetEventSlim` instead of the `AutoResetEvent`.

**Comment by maartenba** [comment]
Seems like it indeed is not. Feel free to do a PR that removes it.

**Comment by maartenba** [comment]
Fixed with #121 - thanks!
