### ISSUE TITLE
Beacon url change, POST and debug

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#120]
According to the: https://developers.google.com/analytics/devguides/collection/protocol/v1/reference the BeaconUrl:
- https://www.google-analytics.com/collect is for HTTPS now.
- The HTTPS is recommended, so it should be default.
- Also, the POST is recommended, it should be used intead of GET.
- I would welcome the ability to set debug (validating) URL https://www.google-analytics.com/debug/collect

I may provide PR to fix all or some of these points.

**Comment by maartenba** [comment]
PR welcome :-)
