### ISSUE TITLE
ApplicationVersion in every tracking

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#124]
I would like to have `ApplicationVersion` (and `ApplicationName`)  in every tracking, not only in the `ScreenviewTracking`. I know I can easily extend every tracking class, but is there any way?
E.g.:
- Make some kid of decorators, to be able to mush up the 'Tracking' classes without extending (Just a very rough idea, I do not know how to do it yet.)
- Put the `IAppTrackingParameters` to `GeneralParameters`.
- Make some volatile `TrackerBase.EnhanceParameters()` to be able to make a subclass and provide own default parameters.

**Comment by maartenba** [comment]
Maybe extend `TrackerBase` or `SimpleTracker` and then add these properties for every request? Or some sort of `DefaultParameters` collection that is always sent over the wire (but can be overloaded by each event if needed)

**Comment by xmedeko** [comment]
Yes, maybe the `TrackerBase.DefaultParameters` would be the best, but rather as a class with `[Beacon]` attributes than string Dictionary. Then the `TrackAsync` may call `GetParametersDictionary` twice and union the results. Also, some or all code from `SetRequired` may be moved to the `DefaultParameters`.

**Comment by maartenba** [comment]
Feel free to come up with a simple example we can discuss on, sounds like somethign that can be added

**Comment by xmedeko** [comment]
Now, looking at the [Google doc App Tracking](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#apptracking) the Supported Hit Types is all. What is the reason the `IAppTrackingParameters` is not in the `IGeneralParameters`?

**Comment by gandarez** [comment]
Because `This field is required for any hit that has app related data`. Since app related data is not present, in my opinion it shouldn't be in `IGeneralParameters`

**Comment by xmedeko** [comment]
Since `GeneralParameters` is a fat class, it includes many interfaces, like `ITrafficSourcesParameters`, `ICustomDimensionParameters`, etc. Then IMHO it should contain the `IAppTrackingParameters`, too.

Other approach is to have the base class like `GeneralParameters` slim. Then I agree it should not contain the `IAppTrackingParameters`, but also some other interfaces, too.
