### ISSUE TITLE
Add Beacon DefaultValue and use non-nullable types

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#134]
Following changes in #132 many or all nullable `bool?` may be changed to non-nullable `bool` when something like [`DefaultAttribute`](https://msdn.microsoft.com/en-us/library/system.componentmodel.defaultvalueattribute(v=vs.110).aspx) is used. E.g.
```c#
[Beacon("exf")] 
[DefaultValue(true)]
public bool IsFatal { get; set; }

[Beacon("ni")]
[DefaultValue(false)]
public bool NonInteractionHit { get; set; }
```
So, then the `value == DefaultValue`, then the property is not sent in the HTTP request. 

Note: it may be applied to the `TransactionRevenue`, `TransactionShipping`, `TransactionTax`, too.

**Comment by gandarez** [comment]
The problem as I said in the other thread is that not all parameters are (or none) required.

**Comment by xmedeko** [comment]
For some parameters, if they are not included in the request, they are treated like they have the default value. E.g. if you omit `exf`, then it's the same as sending `exf=1`. Hence, we do not need 3 values: `null, false, true`. We may have just `false, true` and specify, that if the parameter is `true` then it means do not send it.

**Comment by maartenba** [comment]
Could there be cases where the value still has to be sent, even if it's the default value?
To be honest I'm not sure this one *needs* changing?

**Comment by xmedeko** [comment]
No, if the field has default value, it do not need to be send. Some fields have default value `None` in the doc, so they should be nullable types in C# (if they are optional). And the library do not sent `null`, although it may send it. Those fields, who has defined some certain default value, do not need to be nullable C#.

As I have written, this one _does not needs_ changing, IMO it's just a _nicer_ to have non-nullable bools in C# since it's easier to use and understand them. Otherwise, the user must read the doc to know, what the `null` means (i.e. what happen, if the value is not set). E.g. `IsFatal` flag - if the code does not set it, is the exception fatal or not?

Also, it saves a bit of the HTTP request size if someone is setting these to default values in their code.

**Comment by maartenba** [comment]
My vote is on not changing this one for now, as there are in essence indeed three states (not specified/default, explicitly specified: true, false). Ok with everyone?
(open for discussion but personally don't see the merit other than nice code to look at :-))

**Comment by xmedeko** [comment]
I am ok with not changing. It's a minor benefit for me.

I just disagree with:
* This way, with default value, the HTTP request is never bigger, but it may be **smaller** is the user sets the state, which is default.
* In essence, the protocol itself has three states, but the Google Analytics (server) has two states (1, 0). IMO the client states should be made by the  server states, not by the protocol abilities. It's not about nicer code, but about the code clarity, too.

**Comment by maartenba** [comment]
Ok will close for now, but can always be reopened if we need it later.
