### ISSUE TITLE
Decimal convestion is wrong for non-us Culture

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#135]
`decimal` is used in the EComerce classes. However, it's conversion to string depends on the current thread culture. E.g.
```c#
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("de-DE");
decimal value = 16325.62m;
Console.WriteLine(value.ToString());
```

I think the `value.ToString(System.Globalization.CultureInfo.InvariantCulture)` should be called.

**Comment by gandarez** [comment]
Give me a piece of code where it happens

**Comment by xmedeko** [comment]
[`TrackerBase.GetParametersDictionary`](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerBase.async.cs#L50)
