### ISSUE TITLE
The given filter instance must implement one or more of the following filter interfaces

### ISSUE THREAD

**Issue by SamRizvi** [maartenba/GoogleAnalyticsTracker#138]
I try to add the Tracking filter as given below in FilterConfig registration . 

`filters.Add(new ActionTrackingAttribute(configTrackingId, configDomain));`. 

When executing application the following exception occurs on the filter add code above. 

`The given filter instance must implement one or more of the following filter interfaces: System.Web.Mvc.IAuthorizationFilter, System.Web.Mvc.IActionFilter, System.Web.Mvc.IResultFilter, System.Web.Mvc.IExceptionFilter, System.Web.Mvc.Filters.IAuthenticationFilter. 
`

**Comment by maartenba** [comment]
May be using the WebAPI version instead of the MVC version. Try a different NuGet package :-)
