### ISSUE TITLE
Strong Name DLLs in NuGet

### ISSUE THREAD

**Issue by MikeAtETI** [maartenba/GoogleAnalyticsTracker#139]
Can the DLLs in the NuGet packages get strong names?

**Comment by xmedeko** [comment]
Better not to, e.g. see https://github.com/MahApps/MahApps.Metro/blob/develop/docs/release-notes/1.6.0.md#breaking-change

You can compile strong named DLL by yourself, or use the [Strong Namer](https://github.com/dsplaisted/strongnamer) or [Strong-Name Signer](https://github.com/brutaldev/StrongNameSigner).

**Comment by maartenba** [comment]
All are strong named starting with v5.0
