### ISSUE TITLE
Setting EventTracking.Value fails with InvalidCastException

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#140]
When creating `EventTracking` with a` Value, then it fails with InvalidCastException in the [TrackerBase.GetParametersDictionary() line 41](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerBase.async.cs#L41). The problem is that any `Nullable.GetUnderlyingType` is assumed as `bool`.

@gandarez See our debate in #132 about the `bool` and `bool?` checking.

**Comment by supercar1000** [comment]
+1

**Comment by maartenba** [comment]
Any quick repro?

**Comment by maartenba** [comment]
Nevermind, got it. I just pushed an update to NuGet which should fix this - version `4.5.0-beta-00013`
