### ISSUE TITLE
Does this library support eCommerce transactions?

### ISSUE THREAD

**Issue by YodasMyDad** [maartenba/GoogleAnalyticsTracker#142]
So we can post the data via your library and the transactions will appear in Analytics. Also, will it tie in with Adwords? i.e. If the transaction came from Adwords?

**Comment by maartenba** [comment]
It does!

**Comment by maartenba** [comment]
You can track an [`ECommerceTransaction`](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerParameters/ECommerceTransaction.cs) to do this. Call [`TrackAsync`](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerBase.async.cs#L125) and pass it in.
