### ISSUE TITLE
OS Version/Platform is not visible in Analytics

### ISSUE THREAD

**Issue by jannik-mohemian** [maartenba/GoogleAnalyticsTracker#143]
I am sending a request using the following setup.

```c#
public string ApplicationVersion => Assembly.GetExecutingAssembly().GetName().Version.ToString();
public string OperatingSystem => Environment.OSVersion.Platform.ToString();
public string OperatingSystemVersionNumber => Environment.OSVersion.Version.ToString();
```

```c#
var env = new SimpleTrackerEnvironment(OperatingSystem, OperatingSystemVersionNumber, ApplicationVersion);
var tracker = new SimpleTracker("UA-XXX", env);
```

```c#
await tracker.TrackPageViewAsync("bar", "foo", customDimensions);
```

Yet in analytics the Operating System area stays empty.

<img width="497" alt="screen shot 2018-03-27 at 15 11 41" src="https://user-images.githubusercontent.com/22029725/37969708-b0a68a90-31d1-11e8-84d5-30987cd9de03.png">

---

- Can you send any string as a version number/string or do you have to follow specific requirements?
- Does the automatic user-agent generation using these parameters still work or has something changed on Google Analytics side?

**Comment by jannik-mohemian** [comment]
**Update:** Now it's showing the User Agent as `not set`

<img width="159" alt="screen shot 2018-03-27 at 16 32 09" src="https://user-images.githubusercontent.com/22029725/37974170-86548d5e-31dc-11e8-9d73-0ef1c1a5bd6d.png">

_Will try known User Agent manually..._

**Comment by jannik-mohemian** [comment]
_Issue can be closed_

I figured out how to add custom parameters to the tracking requests. Maybe the `.UserAgent` is not shown correctly when setting up the Google Analytics project as an `App` instead of `Website`.

**Comment by maartenba** [comment]
Ah yes that will be the issue! Website is indeed required.
