### ISSUE TITLE
Significant (~5 seconds) delay on an attempt to Log an event if DNS isn't answering

### ISSUE THREAD

**Issue by Shaddix** [maartenba/GoogleAnalyticsTracker#144]
This mainly applies to 
> Windows applications (WinForms, WPF, Console):

If the PC is connected to the network, but not to the Internet (e.g. local network) and DNS isn't able to resolve "www.google-analytics.com", then every request to TrackerBase.TrackAsync takes a lot of time (~5 seconds).

If there's no internet at all TrackAsync is instant.

It seems that WebRequest locks the main thread while resolving domain.
Adding
> 127.0.0.1 www.google-analytics.com

to Hosts helps.

Btw, HttpClient doesn't have such issue

**Comment by Shaddix** [comment]
Here's the fix (migrating to HttpClient), if you're interested
https://github.com/Shaddix/GoogleAnalyticsTracker/commit/f56f844ded9bb6470ed8ea4bc18a5600e910cbaf

**Comment by maartenba** [comment]
A PR is definitely welcome
