### ISSUE TITLE
Anonymous IP Address Support

### ISSUE THREAD

**Issue by Nuluvius** [maartenba/GoogleAnalyticsTracker#146]
Is there current support for this, if so how might it be accomplished?

Reference [GDPR](https://www.eugdpr.org/) compliance.

**Comment by maartenba** [comment]
You could pass it as a custom parameter when sending data.

**Comment by Nuluvius** [comment]
Could you provide an example please?

**Comment by maartenba** [comment]
I assume you are referring to Anonymous IP tracking in Google Analytics? Or something else?
https://support.google.com/analytics/answer/2763052?hl=en

**Comment by Nuluvius** [comment]
Yes that's exactly right.

**Comment by maartenba** [comment]
You can set that as a parameter on the pageview (and other events):

```
        public static async Task<TrackingResult> TrackPageViewAnonymizeIpAsync(this SimpleTracker tracker, string pageTitle, string pageUrl, IDictionary<int,string> customDimensions)
        {
            var pageViewParameters = new PageView
            {
                DocumentTitle = pageTitle,
                DocumentLocationUrl = pageUrl,
                AnonymizeIp = true
            };

            pageViewParameters.SetCustomDimensions(customDimensions);

            return await tracker.TrackAsync(pageViewParameters);
        }
```

**Comment by Nuluvius** [comment]
Excellent, thanks.

What about in version 1.8.5? Unfortunately I am limited .NET 4.0 due to environmental constraints.

**Comment by maartenba** [comment]
Not sure it is possible there, that version was quite locked down.

**Comment by Nuluvius** [comment]
Yeah, it did look that way, thought I would check anyway. I creating my own very simple wrapper in the end. Thank you for your time anyway!
