### ISSUE TITLE
Support for user IDs?

### ISSUE THREAD

**Issue by Zifrian** [maartenba/GoogleAnalyticsTracker#149]
I implemented a simple tracker for my desktop application and it doesn't work as well for users as tracking website users as unique (new/returning). 

It seems GA allows a userid system but I can't find the option in your library. Does it support sending in unique user ids? The reason I'm asking is basic, every time someone opens my application it registers as a new user but I'd like to know how many unique users I have. 

Thanks

**Comment by maartenba** [comment]
You can pass it in from the `GeneralParameters` - https://github.com/maartenba/GoogleAnalyticsTracker/blob/b7710a3c7703cdefc29e59721d6b25eaae385c76/GoogleAnalyticsTracker.Core/TrackerParameters/GeneralParameters.cs#L101

**Comment by Zifrian** [comment]
Thanks, much appreciated.

**Comment by ShammyLevva** [comment]
Can you give an example of what you mean by "pass it in from the GeneralParameters" please?

I'm looking to do exactly the same thing. At present I have...
                OperatingSystem os = Environment.OSVersion;
                SimpleTrackerEnvironment ste = new SimpleTrackerEnvironment(os.Platform.ToString(), os.Version.ToString(), os.VersionString);
                SimpleTracker st = new SimpleTracker("UA number here", ste);
                TrackingResult x = await st.TrackPageViewAsync("site name hete", "site url here", null);

I'm assuming it needs to be in where the null is in trackpageviewasync but I've been unable to get to grasp with the correct syntax required.

**Comment by maartenba** [comment]
Indeed, the third parameter to `TrackPageViewAsync` will give you access to set it. Adding just the one property you need is ookay, all else should be "default".

**Comment by Zifrian** [comment]
Just to be clear, I have my UserID ("GA Code" above in code snip), maybe I should have asked if we can track Client ID? Thanks

**Comment by maartenba** [comment]
You can pass parameters to the `TrackEventAsync()` method, and in those parameters set the `UserId` property to whatever you want to set it.
