### ISSUE TITLE
C# Winforms Example for Creating Unique Session

### ISSUE THREAD

**Issue by belliez** [maartenba/GoogleAnalyticsTracker#150]
Please can you give an example how I can implement unique session tracking for c# winforms for SimpleTracker.    See a post I have with my existing code:
https://stackoverflow.com/questions/55238035/c-sharp-googleanalyticstracker-create-unique-session-for-winforms-application#55238035

Thanks

**Comment by maartenba** [comment]
You will want to set the user ID property, much like here: https://github.com/maartenba/GoogleAnalyticsTracker/issues/149
