### ISSUE TITLE
Is there an ASP.NET Core MVC 6 Sample? or will that not be included?

### ISSUE THREAD

**Issue by MypowerHD** [maartenba/GoogleAnalyticsTracker#152]
Hey there, will be ASP.NET Core MVC6 supported in any time?

**Comment by maartenba** [comment]
You can use the Simple tracker and hook it into an IActionFilter.

**Comment by maartenba** [comment]
Closing issue for now. Feel free to re-open if still needed. (do check https://github.com/maartenba/GoogleAnalyticsTracker/pull/154 for newer MVC vrsions)
