### ISSUE TITLE
Does this library support Enhanced e-Commerce?

### ISSUE THREAD

**Issue by modemaizer** [maartenba/GoogleAnalyticsTracker#156]
Can we send parameters of the Enhanced E-Commerce, such as list of products with their parameters ('pr1id', 'pr1nm', 'pr1cd4', etc.)?

These parameters are described [here](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#enhanced-ecomm).

**Comment by maartenba** [comment]
You can track an [`ECommerceTransaction`](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerParameters/ECommerceTransaction.cs) to do this. Call [`TrackAsync`](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerBase.async.cs#L125) and pass it in.

**Comment by modemaizer** [comment]
But there are no ability to add products in ECommerceTransaction...

**Comment by modemaizer** [comment]
Anyway, I just finished implement it.

**Comment by maartenba** [comment]
ECommerceItem can be used?

**Comment by modemaizer** [comment]
No, it isn't compatible with Enhanced E-Commerce unfortunately

**Comment by maartenba** [comment]
Got it. Will have a look at your PR in a bit, thanks in advance!

**Comment by maartenba** [comment]
And merged. Thanks, @modemaizer!
