### ISSUE TITLE
Dependency injection fails in a netcoreapp3.1 WebAPI

### ISSUE THREAD

**Issue by xfischer** [maartenba/GoogleAnalyticsTracker#162]
Hi ! First, thank you for this project, it's helping me a lot.
I have some issues when adding GoogleAnalyticsTracker in a ASP.Net Core Web API running under netcore3.1.

I have this error when I run the WebAPI on ```CreateHostBuilder(args).Build().Run();``` : 

> System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: GoogleAnalyticsTracker.AspNet.GoogleAnalyticsTrackerMiddleware Lifetime: Scoped ImplementationType: GoogleAnalyticsTracker.AspNet.GoogleAnalyticsTrackerMiddleware': Unable to resolve service for type 'Microsoft.AspNetCore.Http.RequestDelegate' while attempting to activate 'GoogleAnalyticsTracker.AspNet.GoogleAnalyticsTrackerMiddleware'.)'

I have tried to move ```app.UseGoogleAnalyticsTracker();``` and ```services.AddGoogleAnalyticsTracker``` up and down with no luck.

(I run the code from a fork from this commit: https://github.com/maartenba/GoogleAnalyticsTracker/commit/64239b923d55140d273dc6e53831f789d5ae6452)

Projects referenced:
- GoogleAnalyticsTracker.AspNetCore
- GoogleAnalyticsTracker.Core

Are you aware of this issue ?

**Comment by maartenba** [comment]
Now I am :-) Will investigate, thanks!

**Comment by maartenba** [comment]
Updated, version 6.0.1 on NuGet has the fix.

**Comment by xfischer** [comment]
Thanks @maartenba ! Fast response! I will try it today and I’ll let you know. 
Btw I didn’t find your packages in Nuget (this is why I forked) can you point them out ?
