### ISSUE TITLE
[Question] asp.net core CustomizeAnalyticsSession

### ISSUE THREAD

**Issue by philipraets** [maartenba/GoogleAnalyticsTracker#163]
Hi,

I'm trying to implement GoogleAnalyticsTracker in an asp.net core 3.1 MVC project, and everything is working so far.
However I don't know how to implement the CustomizeAnalyticsSession so I don't have a unique visitor per pageview

My code so far:

in Startup.cs:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddGoogleAnalyticsTracker(options => {
		options.TrackerId = Configuration["GoogleAnalytics:UATrackingID"];
		options.ShouldTrackRequestInMiddleware = TrackRequests.No;
	});
    ....
}
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	app.UseGoogleAnalyticsTracker();
        ....
}
```

and in my controllers:
```
[HttpGet]
[TrackPageView(Enabled = true)]

[HttpPost]
[TrackEvent(Enabled = true, Category = "Formulier", Action = "Verzenden", ActionDescription = "Probio")]

```
I understand that I can give an option in Startup.cs like "options.CustomizeAnalyticsSession", but I don't know what to do with this.

Thx,

Philip

**Comment by maartenba** [comment]
That callback allows you to either customize the session hat is passed in as a parameter, or return a custom `IAnalyticsSession` instance you created.

I'd recommend looking into https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/AnalyticsSession.cs, and create your own class similar to this. The `SessionId` is I think what is causing separate visits in your case, returning the same value for the same user there is what will make things work as expected.

**Comment by philipraets** [comment]
Thanks,

I've created a class, but how do I tell "AddGoogleAnalyticsTracker" in startup.cs to use this class?

(Sorry, still very new to programming and learning a lot)

**Comment by maartenba** [comment]
In the callback, you can return a `new YourSpecificClass()` (or call into a method that adds the required data to it).

Very much pseudo-code:
```
// ...
options.CustomizeAnalyticsSession = defaultSession => new YourSpecificClass();
// ...
```

**Comment by Mutwiri254** [comment]
Hi i seem to have followed the instructions well but i still have the same problem of every event and pages being tracked generates a new user.
Here is my startup.cs file 
![image](https://user-images.githubusercontent.com/71402329/126484861-5148d643-fbd3-4687-a69d-33985631ced5.png)
With the AnalyticsSession class named session https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/AnalyticsSession.cs
 And my controller sample is 
![image](https://user-images.githubusercontent.com/71402329/126485259-00e7940c-5d72-4ad5-a7b2-13346e3e4cd1.png)

Where could i be wrong?
