### ISSUE TITLE
Google Analytics has updated.

### ISSUE THREAD

**Issue by GingerLi** [maartenba/GoogleAnalyticsTracker#164]
Dear Maartenba,
I found Google Analytics has updated and I can't create a new property that has a tracking id like "UA-XXXXXX-XX". Now the new property's tracking id like "XXXXXXXX", just can't receive data with your great library. I've been using your library for a long time. It used to work very well. Will you update the project?

**Comment by GingerLi** [comment]
Thanks for your response. It seems it is a v4 property and the new property could have streams with ids like "G-XXXXXXXX", but still can't receive data.

**Comment by maartenba** [comment]
Yeah seeing the same on a test property I created. The JS snippet for those is different too, so looks like the API Google analytics tracker uses is not the right one for these new properties

**Comment by GingerLi** [comment]
Dear Maartenba, I found we can still create an old "UA-XXXXX-XX" property following this: https://support.google.com/analytics/answer/10269537.
But it seems Google will abandon the old version property someday.

**Comment by maartenba** [comment]
Nice! So I guess that works for you now?

**Comment by GingerLi** [comment]
Yes. It works now. :)

**Comment by marcusbooyah** [comment]
Looks like the Measurement Protocol changed for GA4: https://developers.google.com/analytics/devguides/collection/protocol/ga4

Currently the API is in alpha status due to [these limitations](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/limitations)

**Comment by cklenk** [comment]
Hello, wondering if anyone thinks this will support GA4, and if so, is there any sort of timeline?

Thanks

**Comment by maartenba** [comment]
@cklenk no such plans right now due to time constraints. Might happen at some point, for now downgrading the account is probably easiest.

**Comment by theindra** [comment]
I would also appreciate support for GA4.

**Comment by maartenba** [comment]
Closing this issue in favor of #172
