### ISSUE TITLE
Trailing `&` may cause issues

### ISSUE THREAD

**Issue by marklagendijk** [maartenba/GoogleAnalyticsTracker#166]
I'm currently in the process of investigating a drop in certain of our Google Analytics data that occurred when we migrated to .NET 5 and with that also upgraded this library to 5.x to 6.x.

As you know Google Analytics' `/collect` endpoint does not return errors for invalid requests. I found out that there is a `/debug/collect` endpoint which will report these errors.

To find the cause of the drop in data I created a `DelegatingHandler` that will call both the `/collect` endpoint and the `/debug/collect` endpoint with the same request, when a request is made.
I then pass a custom HttpClient with this handler to the tracker:
```c#
tracker.HttpClient = new HttpClient(_googleAnalyticsDebugHttpMessageHandler);
```

So far I found one issue using this approach. The debug endpoint complains with a weird message (although it does say that the request is valid):
```json
{
  "hitParsingResult": [ {
    "valid": true,
    "parserMessage": [ {
      "messageType": "INFO",
      "description": "Unrecognized parameter '_anon_uip' found.",
      "messageCode": "UNKNOWN_PARAMETER",
      "parameter": "_anon_uip"
    } ],
    "hit": "/debug/collect?v=1\u0026tid=UA-REDACTEDu0026cid=930587ff-f066-4766-85ca-fdbdc9b56711\u0026t=event\u0026cd2=3\u0026ea=MyAction\u0026ec=MyCategory\u0026el=37825\u0026ev=37825\u0026ni=1\u0026uip=xxxxxxxxx\u0026_anon_uip=127.0.0.0"
  } ],
  "parserMessage": [ {
    "messageType": "INFO",
    "description": "Found 1 hit in the request."
  } ]
}
```
You can try this yourself by going to the following url (Note: you need to fill in a valid tracking account id):
```
https://www.google-analytics.com/debug/collect?v=1&tid=UA-REDACTED&cid=a785beb3-1af4-4d2e-b050-e29529d95150&t=event&cd2=3&ea=MyAction&ec=MyCategory&el=MyLabel&ev=123&ni=1&uip=127.0.0.1&
```

The issue is caused by the fact that this library sends a trailing `&` at the end of the request data. This happens on [this line](https://github.com/maartenba/GoogleAnalyticsTracker/blob/master/GoogleAnalyticsTracker.Core/TrackerBase.cs#L70).

When doing the same request without the trailing `&` the validation message disappears.

So far it is unclear what the impact of this issue is, but I think it would be best to fix it.
I can create a PR.

**Comment by maartenba** [comment]
Thanks for the suggestion and fix! Will have a look at it tonight and merge the update in.

**Comment by marklagendijk** [comment]
Thanks for the quick merge and release!
