### ISSUE TITLE
implement a custom IAnalyticsSession

### ISSUE THREAD

**Issue by Mutwiri254** [maartenba/GoogleAnalyticsTracker#169]
Hi,
I am having an issue with tracking sessions and users, for my case every event or page view tracked counts as a new user, i am requesting how best i can implement this to be able to track sessions. 
Below is an example screenshot of one session with one user but it indicates five users which should not be the case. 

![image](https://user-images.githubusercontent.com/71402329/126470330-85d55387-04d2-40d1-92ba-39fd41f2fb69.png)

**Comment by maartenba** [comment]
Please see #163 and/or #150

**Comment by Mutwiri254** [comment]
Well noted, however;
https://github.com/maartenba/GoogleAnalyticsTracker/issues/163#issuecomment-884134980

**Comment by maartenba** [comment]
The `GetUniqueVisitorId` method by default returns a random new user id every time. If you plug any static I'd based on your actual user, this should return the same user each time.

**Comment by Mutwiri254** [comment]
I now get it, my apologies for bothering you, i am new in programming, so in my case i would like to plug a static id of IPAddress of the user, that is IpAddress is the static.
How can i implement the method ? for my case.

**Comment by maartenba** [comment]
No worries. It will have to be a number, you could store it in an asp.net core session for each user.

**Comment by Mutwiri254** [comment]
Thanks a lot, please do you have code sample on how to do it.

**Comment by Mutwiri254** [comment]
Hello, 
Can i get a code sample on how to implement a static id on the GetUniqueVisitorId please as requested.
I am stuck on that for sometime now with no idea on  how to implement.

**Comment by maartenba** [comment]
Sorry, busy days here. The idea would be to have one user have the same ID all the time. You could set a cookie if it's not present, and uset he value from that cookie as the id here.
