### ISSUE TITLE
TrackerCore is showing version 1.0.0.0 instead of 7.0.0.0

### ISSUE THREAD

**Issue by michalkrupiarz** [maartenba/GoogleAnalyticsTracker#171]
We haveu pdated recently from 6.0.5 to 7.0.0 but it is showing as version 1.0.0.0 instead of version 6.0.0.0 in csproj file

**Comment by maartenba** [comment]
Just pushed out 7.0.1, this should fix things. Good catch!

**Comment by michalkrupiarz** [comment]
Thank you. It worked.
