### ISSUE TITLE
Track trough Google Measurement Protocol

### ISSUE THREAD

**Issue by derigel23** [maartenba/GoogleAnalyticsTracker#37]
https://developers.google.com/analytics/devguides/collection/protocol/v1/

**Comment by maartenba** [comment]
Just merged https://github.com/maartenba/GoogleAnalyticsTracker/pull/73 which adds this new protocol. Prerelease packages for GoogleAnalyticsTracker 4.0.0 are available from NuGet - please give them a go. (4.0.0-alpha00000 for all packages)
