### ISSUE TITLE
OWIN support

### ISSUE THREAD

**Issue by azzlack** [maartenba/GoogleAnalyticsTracker#75]
I made a middleware for using this with OWIN in a project at my company, I can make a PR that implements this feature if you are interested

**Comment by maartenba** [comment]
That would be wonderful!

**Comment by azzlack** [comment]
Done: https://github.com/maartenba/GoogleAnalyticsTracker/pull/76

**Comment by maartenba** [comment]
@azzlack that is awesome! Will review shortly.
