### ISSUE TITLE
ASP.NET MVC 5 applications

### ISSUE THREAD

**Issue by TomSimonsen** [maartenba/GoogleAnalyticsTracker#77]
Hi!

I'm trying to " Install-Package GoogleAnalyticsTracker.MVC5"  in my MVC project but I got:

Install-Package : Unable to find package 'GoogleAnalyticsTracker.MVC5'.

Thanks,
Tom S.

**Comment by gandarez** [comment]
No problem found. Could you please share more details?

> PM> Install-Package GoogleAnalyticsTracker.MVC5
Attempting to resolve dependency 'GoogleAnalyticsTracker.Core (≥ 4.0.2)'.
Attempting to resolve dependency 'Microsoft.AspNet.Mvc (≥ 5.2.3)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebPages (≥ 3.2.3 && < 3.3.0)'.
Attempting to resolve dependency 'Microsoft.Web.Infrastructure (≥ 1.0.0.0)'.
Attempting to resolve dependency 'Microsoft.AspNet.Razor (≥ 3.2.3 && < 3.3.0)'.
Installing 'GoogleAnalyticsTracker.Core 4.0.2'.
Successfully installed 'GoogleAnalyticsTracker.Core 4.0.2'.
Installing 'Microsoft.AspNet.Razor 3.2.3'.
You are downloading Microsoft.AspNet.Razor from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.Razor 3.2.3'.
Installing 'Microsoft.AspNet.WebPages 3.2.3'.
You are downloading Microsoft.AspNet.WebPages from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebPages 3.2.3'.
Installing 'Microsoft.AspNet.Mvc 5.2.3'.
You are downloading Microsoft.AspNet.Mvc from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.Mvc 5.2.3'.
Installing 'GoogleAnalyticsTracker.MVC5 4.0.2'.
Successfully installed 'GoogleAnalyticsTracker.MVC5 4.0.2'.
Adding 'GoogleAnalyticsTracker.Core 4.0.2' to Gandarez.PagedList.Web.
Successfully added 'GoogleAnalyticsTracker.Core 4.0.2' to Gandarez.PagedList.Web.
Removing 'Microsoft.AspNet.Mvc 5.2.2' from Gandarez.PagedList.Web.
Successfully removed 'Microsoft.AspNet.Mvc 5.2.2' from Gandarez.PagedList.Web.
Removing 'Microsoft.AspNet.WebPages 3.2.2' from Gandarez.PagedList.Web.
Successfully removed 'Microsoft.AspNet.WebPages 3.2.2' from Gandarez.PagedList.Web.
Removing 'Microsoft.AspNet.Razor 3.2.2' from Gandarez.PagedList.Web.
Successfully removed 'Microsoft.AspNet.Razor 3.2.2' from Gandarez.PagedList.Web.
Adding 'Microsoft.AspNet.Razor 3.2.3' to Gandarez.PagedList.Web.
Successfully added 'Microsoft.AspNet.Razor 3.2.3' to Gandarez.PagedList.Web.
Adding 'Microsoft.AspNet.WebPages 3.2.3' to Gandarez.PagedList.Web.
Successfully added 'Microsoft.AspNet.WebPages 3.2.3' to Gandarez.PagedList.Web.
Adding 'Microsoft.AspNet.Mvc 5.2.3' to Gandarez.PagedList.Web.
Successfully added 'Microsoft.AspNet.Mvc 5.2.3' to Gandarez.PagedList.Web.
Adding 'GoogleAnalyticsTracker.MVC5 4.0.2' to Gandarez.PagedList.Web.
Successfully added 'GoogleAnalyticsTracker.MVC5 4.0.2' to Gandarez.PagedList.Web.
Uninstalling 'Microsoft.AspNet.Mvc 5.2.2'.
Successfully uninstalled 'Microsoft.AspNet.Mvc 5.2.2'.
Uninstalling 'Microsoft.AspNet.WebPages 3.2.2'.
Successfully uninstalled 'Microsoft.AspNet.WebPages 3.2.2'.
Uninstalling 'Microsoft.AspNet.Razor 3.2.2'.
Successfully uninstalled 'Microsoft.AspNet.Razor 3.2.2'.
