### ISSUE TITLE
Which do I need to install in my  VS 2012 SharePoint 2013 solution? 

### ISSUE THREAD

**Issue by khha** [maartenba/GoogleAnalyticsTracker#78]
I created a VS 2012 SharePoint 2013 solution. Now I would like to implement some event tracking in some methods. I installed by nuget "ASP.NET Web API v2 applications". I add the using in the top of the page and is OK. When I add this line of code somewhere the solution is not building anymore:

Tracker tracker = new Tracker("UA-XXXXXX-XX", "www.example.org");

Do I used the correct installation? Or do I need to install "ASP.NET Web API v1 applications"?

**Comment by gandarez** [comment]
I'd go by creating a filter to achieve what you need. Try this one below and also if it doesn't work please share more details about the error thrown.

```csharp
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, Inherited = true, AllowMultiple = true)]
public class GoogleAnalyticsUserTiming : UserTimingTrackingAttribute
{
    public GoogleAnalyticsUserTiming(string category, string variable, string label = null)
        : base("UA-XXXXXX-XX", category, variable, label)
    {
        IsTrackableAction = true;
    }        
}

[GoogleAnalyticsUserTiming("Api", "Quotation")]
public IHttpActionResult Post([FromBody]Quote quote)
{
    return new QuoteResult(quote, Request);
}
```
