### ISSUE TITLE
Setting the UserId breaks tracking (WebApi2)

### ISSUE THREAD

**Issue by turowicz** [maartenba/GoogleAnalyticsTracker#82]
The following code triggers a page view only when the userId is 0. How can I make it work?

```
    using (var tracker = new Tracker("UA-XXXXXXXX-X", "xxxxxxxxxx.com", new AspNetWebApiTrackerEnvironment()))
    {
        tracker.Hostname = hostname;
        tracker.UserAgent = userAgent;
        tracker.Language = language;
        tracker.UseSsl = true;

        var pageView = new PageView();
        pageView.DocumentLocationUrl = pathUrl;
        pageView.DocumentPath = path;
        pageView.DocumentTitle = controllerName;
        pageView.ScreenName = controllerName;

        if (userId > 0)
        {
            pageView.UserId = String.Format("User{0}", userId);
        }

        await tracker.TrackPageViewAsync(pageView);
    }
```

**Comment by gandarez** [comment]
@turowicz As you are implementing your own logic you might follow Google Reference https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters
There're several required parameters to be set.

**Comment by turowicz** [comment]
Is there any other way? I was reading the Tracker's source code and I see that by default the User Identity is used. The application I'm trying to add tracking to doesn't use the ASP.NET's built in authentication layer.

**Comment by turowicz** [comment]
OK, the pageView.ClientId was missing
