### ISSUE TITLE
AppTracking class usage

### ISSUE THREAD

**Issue by turowicz** [maartenba/GoogleAnalyticsTracker#83]
I can't find any way of issuing an instance of AppTracking to the GA API. Is that feature not implemented yet?

**Comment by gandarez** [comment]
There's a class for this called AppTracking however it hasn't been implemented yet.

namespace: GoogleAnalyticsTracker.Core.TrackerParameters

**Comment by turowicz** [comment]
I will have a look into implementing it in 30 min, can't promise I'll do it tho

**Comment by turowicz** [comment]
OK I have a workaround like this:

```

class ApplicationTracking : EventTracking
{
    [Beacon("an", false, false)]
    public string ApplicationName { get; set; }

    public override HitType HitType
    {
        get
        {
            return HitType.Screenview;
        }
    }
}

```

**Comment by turowicz** [comment]
My primary problem is that even though I set the clientid and userid I still get 1 active user per request, which is not true, because all those requests are made by the same user (hardcoded constant userid). Any ideas how to fix that?

**Comment by turowicz** [comment]
OK got that to work. Now the location is not showing anything, I do set the IpOverride and AnonymizeIp = false

**Comment by turowicz** [comment]
OK that was because of my local test IP. All good, screen views seem to be working with the workaround. One more thing I had to do is to write my own session to make sure ClientID was tied to UserID.

```
class ApplicationTrackingSession : AnalyticsSession
{
    readonly Int64 _userId;

    public MailcloudTrackingSession(Int64 userId)
    {
        _userId = userId;
    }

    static Guid IntToGuid(Int64 value)
    {
        byte[] bytes = new byte[16];
        BitConverter.GetBytes(value).CopyTo(bytes, 0);
        return new Guid(bytes);
    }

    public override String GenerateSessionId()
    {
        return IntToGuid(_userId).ToString();
    }
}

```
