### ISSUE TITLE
Request is not available in this context

### ISSUE THREAD

**Issue by nastassiar** [maartenba/GoogleAnalyticsTracker#84]
I know there is already a similar question, but it did not resolve my problem. 

I am trying to use GoogleAnalyticsTracker.MVC4 version 4.04 with Microsoft ASP.NET MVC4 version 4.0.3 and Microsoft ASP.NET Web Pages 2 version 2.0.3.

So I install GoogleAnalyticsTracker.MVC4 and GoogleAnalyticsTracker.Core 4.04

I add the following code to my global configuration file
```csharp
 public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
            filters.Add(new ActionTrackingAttribute(
            "UA-XXXXXXXXX", "https://test.com",
            action => action.ControllerDescriptor.ControllerName == "Api")
        );
        }
```
I had to drop action.ControllerContext from the code to get it to compile.

When I try to run it I get the following error:

Request is not available in this context

   at System.Web.HttpContext.get_Request()
   at GoogleAnalyticsTracker.Mvc4.AspNetMvc4TrackerEnvironment..ctor()
   at GoogleAnalyticsTracker.Mvc4.ActionTrackingAttribute..ctor(String trackingAccount, String trackingDomain, Func`2 isTrackableAction)
   at Test.Web.Api.FilterConfig.RegisterGlobalFilters(GlobalFilterCollection filters) in c:\Users\Test\Documents\test.web\Src\Test.Web.Api\App_Start\FilterConfig.cs:line 13
   at Test.Web.Api.WebApiApplication.Application_Start() in c:\Users\Test\Documents\test.web\Src\Test.Web.Api\Global.asax.cs:line 58

Am i doing something wrong?

**Comment by nastassiar** [comment]
Looks like there is a fix for the issue.
https://github.com/maartenba/GoogleAnalyticsTracker/commit/1dcf540a20b2d4888c8c66c24b09db11fdee82ed

It just hasn't ended up in MVC4 or 5 I'll create a pull request for it as soon as I have time.

**Comment by gandarez** [comment]
@nastassiar I've done this implementation into https://github.com/maartenba/GoogleAnalyticsTracker/commit/5f65158a929df9ad576d67ab2346057310b7ab68

@maartenba could you please upload a new package to NuGet.

**Comment by maartenba** [comment]
Consider it done!

**Comment by gandarez** [comment]
v4.0.5 uploaded.
