### ISSUE TITLE
Returning users in WPF

### ISSUE THREAD

**Issue by MephestoKhaan** [maartenba/GoogleAnalyticsTracker#85]
Is there a way to enable returning users in with the Simple tracker?

I am using WPF and nituced that, when implementing the IAnalyticsSession there is this method:

    string IAnalyticsSession.GenerateCookieValue()

I was expecting that if I returned the same value for an user here it will not recognize him as a new user always, but the code is never called.

I am inheriting from AnalyticsSession and implementing it very much in the same way as the WP8 code (but using Properties.Settings.Default instead). And when I am sending a page I also set:

    
    page.ClientId = Properties.Settings.Default.UniqueID; //this is the same as the unique visitor id

Still no joy, every new visit means a new user

**Comment by gandarez** [comment]
You're right. The method GenerateCookieValue() is obsolete. We didn't take it out when implemented Measurement Protocol. Try overriding GenerateSessionId to implement your logic.

**Comment by MephestoKhaan** [comment]
I am creating a unique session id (guid) per execution and a unique visitor id for the whole installation, but somehow every session registers a new user, even though I am always using the same visitor id.

    private static string sessionID = null;
        public override string GenerateSessionId()
        {
            if (sessionID == null)
            {
                sessionID = base.GenerateSessionId();
            }
            return sessionID;
        }

    protected override string GetUniqueVisitorId()
        {
            if (_settings.UniqueID == null
                || _settings.UniqueID.Length == 0)
            {
                _settings.UniqueID = Guid.NewGuid().ToString();
                _settings.Save();
            }
            return (string)_settings.UniqueID;
        }

Maybe I am missing something obvious? Both methods are working as expected.

**Comment by gandarez** [comment]
It seems to be correct as you said. What _settings does?

**Comment by MephestoKhaan** [comment]
Settings is the WPF Properties.Settings.Default, basically it keeps it saved.

Does the ClientID needs to be equivalent to the session or visitor id?

**Comment by gandarez** [comment]
CID should be a random UUID (version 4) as described in http://www.ietf.org/rfc/rfc4122.txt

**Comment by MephestoKhaan** [comment]
It is one, it just happens to be the same as the value returned by GetUniqueVisitorId() (which is unique per installation). I will try to make it a different one and see what happens. thanks!

**Comment by gandarez** [comment]
@MephestoKhaan http://www.gravitatedesign.com/blog/what-are-sessions-users-google-analytics/

**Comment by AnderssonPeter** [comment]
There is no point in setting `page.ClientId` as its overwritten in `TrackAsync` with `this.AnalyticsSession.GenerateSessionId()`.

So ensure that your `WPFAnalyticsSession.GenerateSessionId()` returns the ClientId that you generated for each new installation.
