### ISSUE TITLE
Using custom dimensions/metrics

### ISSUE THREAD

**Issue by azzlack** [maartenba/GoogleAnalyticsTracker#86]
How would you go about using custom metrics as described here: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cm_ ?

Since you are using reflection to get all `Beacon` attributes, it seems it would be enough to override the PageView class and add some custom properties with corresponding Beacon attributes.

Is this assumption correct? If not, is there another way?

**Comment by azzlack** [comment]
I have tested this now, at works as written above.

Subclass `PageView` and add your own properties and mark them with a `Beacon` attribute and set the name to `cd{index}`.

```csharp
public class CustomPageView : PageView
{
    [Beacon("cd1", false, false)]
    public string System { get; set; }

    [Beacon("cd2", false, false)]
    public string Version { get; set; }
}
```

Don't forget to add the dimensions in Google Analytics as well, or your data will not get stored

**Comment by maartenba** [comment]
Thanks!
