### ISSUE TITLE
Exception and Screenview tracking

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#89]
Hi,
enum `HitType` contains `Screenview` and  `Exception` tracking, but I do not know, hot to track them from `SimpleTracker`.

The `Screenview` is used in the `AppTracking` class (why not `ScreenviewTracking` ?), but there's no `Tracker` method accepting `AppTracking`. What about to make `TrackAsync(IGeneralParameters)` method?

**Comment by gandarez** [comment]
@xmedeko try downloading my forked repo from https://github.com/gandarez/GoogleAnalyticsTracker
I've done few improvements

**Comment by gandarez** [comment]
Also the name of the class was AppTracking because it's used either for App and Screenview.
https://developers.google.com/analytics/devguides/collection/analyticsjs/screens

**Comment by gandarez** [comment]
@xmedeko I've added ExceptionTracking
