### ISSUE TITLE
NonInteractionHit default null

### ISSUE THREAD

**Issue by xmedeko** [maartenba/GoogleAnalyticsTracker#92]
AFAIK sending `ni=0` is pointless, is such case, not sending `ni` at all has same meaning.
So, do not initialize `NonInteractionHit = GoogleBoolean.False` in `GeneralParameters` and `PageView`.

**Comment by gandarez** [comment]
@xmedeko So what's the difference between not sending and initializing it with GoogleBoolean.False?

**Comment by xmedeko** [comment]
The result is same, it's just useless to send `&ni=0` at every request. It's a good rule not to send default values.  There are other default parameters, which are not automatically sent (e.g. `aip`, `qt`).

Beside that, it's also waste of bandwidth, energy, save the planet, ... :-)

**Comment by gandarez** [comment]
@xmedeko get the latest version that I've pushed
