### ISSUE TITLE
What happened to Tracker::SetCustomVariable?

### ISSUE THREAD

**Issue by ryantrem** [maartenba/GoogleAnalyticsTracker#93]
I've been using an older version of GoogleAnalyticsTracker in a Windows Phone app. I'm in the process of updating the app to a Windows 10 Universal app, and so have switched to the newest build of GoogleAnalyticsTracker.RT, but have found that the interface has changed significantly. My main question is, where did Tracker::SetCustomVariable go, or how do I do the equivalent with the new API?

Also, I saw that Tracker::TraceEvent and Tracker::TrackPageView are gone now, but there is a general TrackAsync method. It looks like for most of the packages (e.g. MVC5, etc.) there are extension methods for these that under the hood just setup the right generic parameters object to pass along to TrackAsync. Any reason these extension methods doesn't exist for the GoogleAnalyticsTracker.RT package?

Thanks!
Ryan

**Comment by gandarez** [comment]
@ryantrem I'll split your question into 2 answers.

1. The method SetCustomVariables became obsolete since we've migrated to the new interface. What custom variable you need to set? Please refer to GoogleAnalytics.Core.TrackerParameters. There're these "custom variables" already explicitly implemented.

2. You're free to fork this repo and implement this extension class and submit for us. We didn't implement because it's a kind of specific-needs for each developer.

**Comment by ryantrem** [comment]
@gandarez I was using custom variables for OS version, App version, device type, and locale (so that this data was automatically attached to every event). I will take a look at TrackerParameters and see if I can figure out how to use it for standard Google Analytics custom variables.

Thanks!
Ryan

**Comment by gandarez** [comment]
no problem, any doubts feel free to ask again @ryantrem

**Comment by ryantrem** [comment]
I finally got a chance to revisit this but I'm still not seeing where I would put the custom variables. In GoogleAnalytics.Core.TrackerParameters, I see things like EventTracking and PageView, which I believe I use like this:

this.googleAnalytics.TrackAsync(new EventTracking { Category = category, Action = action, Label = label, Value = value });

But I don't see any properties on this object (or the objects in its inheritance hierarchy) that look like they represent individual custom variables, or a custom variable dictionary. What am I missing? @gandarez
