### ISSUE TITLE
User-ID not supported?

### ISSUE THREAD

**Issue by Whit3Tube** [maartenba/GoogleAnalyticsTracker#95]
Please correct me if im wrong but, it seems to me that the User-ID Feature is missing, am i wrong on that? Or am i missing something?

Greetings Whit3

**Comment by gandarez** [comment]
@Whit3Tube it's under

```C#
GoogleAnalyticsTracker.Core.TrackerParameters.GeneralParameters 
````

**Comment by Whit3Tube** [comment]
Tanks a lot! ;D
