### ISSUE TITLE
GoogleAnalyticsTracker.Simple signature.

### ISSUE THREAD

**Issue by esolCrusador** [maartenba/GoogleAnalyticsTracker#96]
Could you please add snk signature to "GoogleAnalyticsTracker.Simple" project.

**Comment by gandarez** [comment]
@esolCrusador please follow this commit https://github.com/maartenba/GoogleAnalyticsTracker/commit/2ac10227211f2853d854be1cb9ff197931496861

It's gonna be uploaded by @maartenba asap.

**Comment by maartenba** [comment]
Package has been pushed. We may want to sign all projects though, and not just one.

**Comment by esolCrusador** [comment]
Thanks a lot!
